/* ═══════════════════════════════════════════════════════════
   OUTFYST — build.js
   ═══════════════════════════════════════════════════════════
   
   Reads environment variables and generates js/config.js
   Run automatically by Vercel during deploy.
   
   ═══════════════════════════════════════════════════════════ */

const fs = require('fs');
const path = require('path');

// Load .env file for local development (skip if vars already set)
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  envContent.split('\n').forEach(function (line) {
    line = line.trim();
    if (!line || line.startsWith('#')) return;
    const [key, ...rest] = line.split('=');
    if (key && !process.env[key.trim()]) {
      process.env[key.trim()] = rest.join('=').trim();
    }
  });
}

const accessKey = process.env.WEB3FORMS_ACCESS_KEY || 'YOUR_ACCESS_KEY_HERE';

const configContent = `/* Auto-generated by build.js — do NOT edit manually */
window.OUTFYST_CONFIG = {
  WEB3FORMS_ACCESS_KEY: '${accessKey}'
};
`;

const outPath = path.join(__dirname, 'js', 'config.js');
fs.writeFileSync(outPath, configContent, 'utf8');

console.log('✓ js/config.js generated');
if (accessKey === 'YOUR_ACCESS_KEY_HERE') {
  console.log('  ⚠ WEB3FORMS_ACCESS_KEY not set — form will show a setup reminder');
} else {
  console.log('  ✓ WEB3FORMS_ACCESS_KEY injected');
}
